#!/usr/bin/env node

var http = require('http');

var options = {
  host: 'localhost',
  port: 3080,
  path: '/query',
  method: 'POST',
  headers: {
    "Accept": "application/json",
    "Content-Type": "application/json"
  }
};

var date = new Date();
var now = date.getTime();

var payload = {
  "start":now - 15 * 60 * 1000,
  "end" : now,
  "count" : 20,
  "collections" : {
    "jmx" : {
      "HeapMemoryUsage used" : {
        "timestamp" : "response.timestamp",
        "field" : "response.value.HeapMemoryUsage.used",
        "qualifiers" : {},
        "operation" : "AVG"
      }
    }, 
  },
};

var req = http.request(options, function(res) {
  console.log('STATUS: ' + res.statusCode);
  console.log('HEADERS: ' + JSON.stringify(res.headers));
  res.setEncoding('utf8');
  res.on('data', function (chunk) {
    console.log('BODY: ' + chunk);
  });
});

req.on('error', function(e) {
  console.log('problem with request: ' + e.message);
});

// write data to request body
req.write(JSON.stringify(payload));
req.end();
