#!/usr/bin/env node

var http = require('http');
var server = process.argv.length > 2 ? process.argv[2] : "localhost";
var options = {
  host: server,
  port: 3080,
  path: '/query',
  method: 'POST',
  headers: {
    "Accept": "application/json",
    "Content-Type": "application/json"
  }
};
var now = Date.now();
var payload = {
  "type" : "query",
  "start": now - 60 * 60 * 1000,
  "end": now,
  "count": 30,
  "collection" : "jmx",
  "groupBy" : {"url.host":1},
  "qualifier" : { "mbean" : "java.lang:type=Memory" },
  "keys" : { "heap used" : "value.HeapMemoryUsage.used" }
};
var req = http.request(options, function(res) {
  console.log('STATUS: ' + res.statusCode);
  console.log('HEADERS: ' + JSON.stringify(res.headers));
  res.setEncoding('utf8');
  res.on('data', function(chunk) {
    console.log('BODY: ' + chunk);
  });
});
req.on('error', function(e) {
  console.log('problem with request: ' + e.message);
});
// write data to request body
req.write(JSON.stringify(payload));
req.end();