#!/usr/bin/env node
var hostname = require('os').hostname();
var http = require('http');

function postEvent(options) {
  var payload = {
    "timestamp": Date.now(),
    "events": [{
      "type": "example",
      "timestamp": Date.now(),
      "duration": 1200,
      "source": hostname,
      "visitor": "a815ee70-df67-11e0-9572-0800200c9a66",
      "session": "aaebf7d5-c80f-4c04-a2b2-e0de618a364d",
      "metrics": {
        "example": [{
          "url": {
            "protocol": "http",
            "host": "iphone.jolira.com",
            "port": "8081",
            "path": "/query/item",
            "params": {
              "product": 73212272,
              "mode": "summary"
            }
          }
        }]
      }
    }]
  };
  var req = http.request(options, function(res) {
    console.log('STATUS: ' + res.statusCode);
    console.log('HEADERS: ' + JSON.stringify(res.headers));
    res.setEncoding('utf8');
    res.on('data', function(chunk) {
      console.log('BODY: ' + chunk);
    });
  });
  req.on('error', function(e) {
    console.log('problem with request: ' + e.message);
  });
  // write data to request body
  req.write(JSON.stringify(payload));
  req.end();
}
var options = {
  host: 'localhost',
  port: 8081,
  path: '/x',
  method: 'POST',
  headers: {
    "Accept": "application/json",
    "Content-Type": "application/json"
  }
};
var count = process.argv.length > 2 ? parseInt(process.argv[2]) : 1;
for (var idx = 0; idx < count; idx++) {
  postEvent(options);
}